server:
  port: 9002
spring:
  application:
    name: provider
  #    name: nacos-payment-provider
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/payment?characterEncoding=utf8&useSSL=true
      username: root
      password: 123
      type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.12:8888
management:
  endpoints:
    web:
      exposure:
        include: '*'


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.az.springcloud.entity